# set base image (host OS)
FROM miloteam/pro

# copy saas configuration
COPY --chown=milo:sudo uwsgi-saas.ini uwsgi.ini

# copy static assets (UI and documentation)
COPY --chown=milo:sudo static/ static/

# modify ui to disable local user
RUN grep -rl ",localUser:\!0" static/ | xargs sed -i.bak "s|,localUser:\!0|,localUser:\!1|"

# if present, bundle the educational license
COPY --chown=milo:sudo *licensefile.skm *license.pub data/

# if present, bundle the Google service account key
COPY --chown=milo:sudo *serviceAccountKey.json .

# start the application
CMD [ "npx", "concurrently", "'sudo rabbitmq-server'", "'uwsgi --ini uwsgi.ini'", "'celery -A worker worker'" ]
