# set base image (host OS)
FROM miloteam/pro

# env variables
ENV LOCAL_USER=false

# if present, bundle the educational license
COPY --chown=milo:sudo *licensefile.skm *license.pub data/

# if present, bundle the Google service account key
COPY --chown=milo:sudo *serviceAccountKey.json .

# start the application
CMD [ "npx", "concurrently", "'sudo rabbitmq-server'", "'uwsgi --ini uwsgi.ini'", "'celery -A worker worker'" ]
